version: "3"
services:
    database:
        image: postgres:14.2-alpine
        container_name: database
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"           
