version: "3.8"
services:
    db:
        container_name: db
        image: postgres:14.2-alpine
        restart: always
        env_file: .env
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"  
        networks:
            - library         
    back:
        container_name: back
        restart: unless-stopped
        build:
            context: .
        command: >
            sh -c "python manage.py makemigrations && 
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - library
networks:
    library:
        name: library
        driver: bridge
